import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding service packages...')

  // Web Development Packages
  const webDevPackages = [
    {
      name: 'Starter',
      slug: 'web-starter',
      category: 'WEB_DEVELOPMENT',
      price: 2500,
      priceDisplay: '$2,500',
      billingType: 'one_time',
      shortDesc: 'Perfect for small businesses and startups',
      description: 'A professional website to establish your online presence. Includes responsive design, basic SEO optimization, and fast hosting setup.',
      features: [
        'Up to 5 pages',
        'Responsive design',
        'Basic SEO',
        'Contact form',
        'Fast hosting setup',
        '1 month support',
      ],
      isPopular: false,
      isActive: true,
      sortOrder: 1,
      estimatedWeeks: 2,
    },
    {
      name: 'Professional',
      slug: 'web-professional',
      category: 'WEB_DEVELOPMENT',
      price: 5000,
      priceDisplay: '$5,000',
      billingType: 'one_time',
      shortDesc: 'Advanced features for growing businesses',
      description: 'A feature-rich website with custom design, CMS integration, and e-commerce capabilities. Perfect for businesses ready to scale.',
      features: [
        'Up to 15 pages',
        'Custom design',
        'Advanced SEO',
        'CMS integration',
        'E-commerce ready',
        'Analytics setup',
        '3 months support',
      ],
      isPopular: true,
      isActive: true,
      sortOrder: 2,
      badge: 'MOST POPULAR',
      estimatedWeeks: 4,
    },
    {
      name: 'Enterprise',
      slug: 'web-enterprise',
      category: 'WEB_DEVELOPMENT',
      price: null,
      priceDisplay: 'Custom',
      billingType: 'one_time',
      shortDesc: 'Full-scale web applications',
      description: 'Custom-built web applications with unlimited pages, advanced integrations, and dedicated support. Perfect for large organizations.',
      features: [
        'Unlimited pages',
        'Custom features',
        'Advanced integrations',
        'Performance optimization',
        'Security hardening',
        'Dedicated support',
        '12 months support',
      ],
      isPopular: false,
      isActive: true,
      sortOrder: 3,
      estimatedWeeks: 8,
    },
  ]

  // iOS App Packages
  const iosPackages = [
    {
      name: 'Basic',
      slug: 'ios-basic',
      category: 'IOS_APP',
      price: 8000,
      priceDisplay: '$8,000',
      billingType: 'one_time',
      shortDesc: 'Simple iOS app for startups',
      description: 'A native iOS application with essential features. Perfect for MVPs and proof of concept.',
      features: [
        'Up to 5 screens',
        'Native iOS design',
        'Basic authentication',
        'Push notifications',
        'App Store submission',
        '1 month support',
      ],
      isPopular: false,
      isActive: true,
      sortOrder: 1,
      estimatedWeeks: 6,
    },
    {
      name: 'Standard',
      slug: 'ios-standard',
      category: 'IOS_APP',
      price: 15000,
      priceDisplay: '$15,000',
      billingType: 'one_time',
      shortDesc: 'Full-featured iOS application',
      description: 'A comprehensive iOS app with custom UI, backend integration, and advanced features.',
      features: [
        'Up to 15 screens',
        'Custom UI/UX design',
        'User authentication',
        'API integration',
        'In-app purchases',
        'Analytics integration',
        '3 months support',
      ],
      isPopular: true,
      isActive: true,
      sortOrder: 2,
      badge: 'MOST POPULAR',
      estimatedWeeks: 10,
    },
    {
      name: 'Enterprise',
      slug: 'ios-enterprise',
      category: 'IOS_APP',
      price: null,
      priceDisplay: 'Custom',
      billingType: 'one_time',
      shortDesc: 'Complex enterprise iOS solutions',
      description: 'Enterprise-grade iOS applications with complex features, integrations, and ongoing support.',
      features: [
        'Unlimited screens',
        'Complex integrations',
        'Offline functionality',
        'Enterprise security',
        'Custom backend',
        'Dedicated support',
        '12 months support',
      ],
      isPopular: false,
      isActive: true,
      sortOrder: 3,
      estimatedWeeks: 16,
    },
  ]

  // Android App Packages
  const androidPackages = [
    {
      name: 'Basic',
      slug: 'android-basic',
      category: 'ANDROID_APP',
      price: 7500,
      priceDisplay: '$7,500',
      billingType: 'one_time',
      shortDesc: 'Simple Android app for startups',
      description: 'A native Android application with essential features. Perfect for MVPs and proof of concept.',
      features: [
        'Up to 5 screens',
        'Material Design UI',
        'Basic authentication',
        'Push notifications',
        'Play Store submission',
        '1 month support',
      ],
      isPopular: false,
      isActive: true,
      sortOrder: 1,
      estimatedWeeks: 6,
    },
    {
      name: 'Standard',
      slug: 'android-standard',
      category: 'ANDROID_APP',
      price: 14000,
      priceDisplay: '$14,000',
      billingType: 'one_time',
      shortDesc: 'Full-featured Android application',
      description: 'A comprehensive Android app with custom UI, backend integration, and advanced features.',
      features: [
        'Up to 15 screens',
        'Custom UI/UX design',
        'User authentication',
        'API integration',
        'In-app purchases',
        'Analytics integration',
        '3 months support',
      ],
      isPopular: true,
      isActive: true,
      sortOrder: 2,
      badge: 'MOST POPULAR',
      estimatedWeeks: 10,
    },
    {
      name: 'Enterprise',
      slug: 'android-enterprise',
      category: 'ANDROID_APP',
      price: null,
      priceDisplay: 'Custom',
      billingType: 'one_time',
      shortDesc: 'Complex enterprise Android solutions',
      description: 'Enterprise-grade Android applications with complex features, integrations, and ongoing support.',
      features: [
        'Unlimited screens',
        'Complex integrations',
        'Offline functionality',
        'Enterprise security',
        'Custom backend',
        'Dedicated support',
        '12 months support',
      ],
      isPopular: false,
      isActive: true,
      sortOrder: 3,
      estimatedWeeks: 16,
    },
  ]

  // Cross-Platform App Packages
  const crossPlatformPackages = [
    {
      name: 'Starter',
      slug: 'cross-platform-starter',
      category: 'CROSS_PLATFORM_APP',
      price: 12000,
      priceDisplay: '$12,000',
      billingType: 'one_time',
      shortDesc: 'iOS & Android from one codebase',
      description: 'A cross-platform mobile app using React Native. Deploy to both iOS and Android from a single codebase.',
      features: [
        'Up to 8 screens',
        'iOS & Android',
        'Shared codebase',
        'Basic authentication',
        'Push notifications',
        'Store submissions',
        '2 months support',
      ],
      isPopular: false,
      isActive: true,
      sortOrder: 1,
      estimatedWeeks: 8,
    },
    {
      name: 'Professional',
      slug: 'cross-platform-professional',
      category: 'CROSS_PLATFORM_APP',
      price: 22000,
      priceDisplay: '$22,000',
      billingType: 'one_time',
      shortDesc: 'Feature-rich cross-platform app',
      description: 'A comprehensive cross-platform app with custom design, advanced features, and backend integration.',
      features: [
        'Up to 20 screens',
        'iOS & Android',
        'Custom UI/UX design',
        'API integration',
        'In-app purchases',
        'Offline support',
        'Analytics',
        '4 months support',
      ],
      isPopular: true,
      isActive: true,
      sortOrder: 2,
      badge: 'BEST VALUE',
      estimatedWeeks: 12,
    },
    {
      name: 'Enterprise',
      slug: 'cross-platform-enterprise',
      category: 'CROSS_PLATFORM_APP',
      price: null,
      priceDisplay: 'Custom',
      billingType: 'one_time',
      shortDesc: 'Enterprise cross-platform solutions',
      description: 'Enterprise-grade cross-platform applications with complex features and dedicated support.',
      features: [
        'Unlimited screens',
        'iOS & Android',
        'Complex integrations',
        'Enterprise security',
        'Custom backend',
        'Performance optimization',
        'Dedicated support',
        '12 months support',
      ],
      isPopular: false,
      isActive: true,
      sortOrder: 3,
      estimatedWeeks: 20,
    },
  ]

  // Desktop App Packages
  const desktopPackages = [
    {
      name: 'Basic',
      slug: 'desktop-basic',
      category: 'DESKTOP_APP',
      price: 10000,
      priceDisplay: '$10,000',
      billingType: 'one_time',
      shortDesc: 'Simple desktop application',
      description: 'A cross-platform desktop application using Electron. Works on Windows, macOS, and Linux.',
      features: [
        'Single platform',
        'Basic UI/UX',
        'Local data storage',
        'Auto-updates',
        'Installer package',
        '1 month support',
      ],
      isPopular: false,
      isActive: true,
      sortOrder: 1,
      estimatedWeeks: 6,
    },
    {
      name: 'Professional',
      slug: 'desktop-professional',
      category: 'DESKTOP_APP',
      price: 20000,
      priceDisplay: '$20,000',
      billingType: 'one_time',
      shortDesc: 'Full-featured desktop application',
      description: 'A feature-rich desktop application with cloud sync, API integration, and multi-platform support.',
      features: [
        'Windows & macOS',
        'Custom UI/UX design',
        'Cloud synchronization',
        'API integration',
        'Database support',
        'Auto-updates',
        '3 months support',
      ],
      isPopular: true,
      isActive: true,
      sortOrder: 2,
      badge: 'MOST POPULAR',
      estimatedWeeks: 10,
    },
    {
      name: 'Enterprise',
      slug: 'desktop-enterprise',
      category: 'DESKTOP_APP',
      price: null,
      priceDisplay: 'Custom',
      billingType: 'one_time',
      shortDesc: 'Enterprise desktop solutions',
      description: 'Enterprise-grade desktop applications with advanced features, security, and dedicated support.',
      features: [
        'All platforms',
        'Complex integrations',
        'Enterprise security',
        'Custom backend',
        'License management',
        'Dedicated support',
        '12 months support',
      ],
      isPopular: false,
      isActive: true,
      sortOrder: 3,
      estimatedWeeks: 16,
    },
  ]

  // 3D Printing Packages
  const printingPackages = [
    {
      name: 'Single Print',
      slug: '3d-single-print',
      category: 'THREE_D_PRINTING',
      price: 25,
      priceDisplay: 'From $25',
      billingType: 'one_time',
      priceNote: 'Price varies by size and material',
      shortDesc: 'One-off custom 3D prints',
      description: 'Perfect for prototypes, gifts, or single custom items. Upload your STL file and we\'ll bring it to life.',
      features: [
        'Any STL file accepted',
        'Multiple materials',
        'Various colors',
        'Quality finishing',
        'Fast turnaround',
        'Shipping included',
      ],
      isPopular: false,
      isActive: true,
      sortOrder: 1,
      estimatedDays: 5,
    },
    {
      name: 'Small Batch',
      slug: '3d-small-batch',
      category: 'THREE_D_PRINTING',
      price: 200,
      priceDisplay: 'From $200',
      billingType: 'one_time',
      priceNote: '10-50 units',
      shortDesc: 'Small production runs',
      description: 'Ideal for small businesses, Etsy sellers, or limited edition items. Consistent quality across all units.',
      features: [
        '10-50 identical units',
        'Bulk pricing discount',
        'Consistent quality',
        'Multiple materials',
        'Custom packaging',
        'Priority support',
      ],
      isPopular: true,
      isActive: true,
      sortOrder: 2,
      badge: 'POPULAR',
      estimatedDays: 14,
    },
    {
      name: 'Production Run',
      slug: '3d-production-run',
      category: 'THREE_D_PRINTING',
      price: null,
      priceDisplay: 'Custom Quote',
      billingType: 'one_time',
      priceNote: '50+ units',
      shortDesc: 'Large-scale manufacturing',
      description: 'Full production runs for businesses. Volume discounts, quality assurance, and dedicated project management.',
      features: [
        '50+ units',
        'Volume discounts',
        'Quality assurance',
        'Dedicated manager',
        'Custom materials',
        'Flexible scheduling',
        'White-label packaging',
      ],
      isPopular: false,
      isActive: true,
      sortOrder: 3,
      estimatedWeeks: 4,
    },
  ]

  const allPackages = [
    ...webDevPackages,
    ...iosPackages,
    ...androidPackages,
    ...crossPlatformPackages,
    ...desktopPackages,
    ...printingPackages,
  ]

  // Delete existing packages first
  console.log('Clearing existing service packages...')
  await prisma.servicePackage.deleteMany({})

  // Insert all packages
  for (const pkg of allPackages) {
    console.log(`Creating package: ${pkg.name} (${pkg.category})`)
    await prisma.servicePackage.create({
      data: {
        name: pkg.name,
        slug: pkg.slug,
        category: pkg.category as any,
        price: pkg.price,
        priceDisplay: pkg.priceDisplay,
        billingType: pkg.billingType,
        priceNote: pkg.priceNote || null,
        shortDesc: pkg.shortDesc,
        description: pkg.description,
        features: pkg.features,
        isPopular: pkg.isPopular,
        isActive: pkg.isActive,
        sortOrder: pkg.sortOrder,
        badge: pkg.badge || null,
        estimatedDays: pkg.estimatedDays || null,
        estimatedWeeks: pkg.estimatedWeeks || null,
      },
    })
  }

  console.log(`Successfully created ${allPackages.length} service packages!`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
